version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus
    volumes:
      - ${PWD}/fs/volumes/prometheus:/etc/prometheus:Z
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - "19090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)"
    ports:
      - "19100:9100"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.1
    container_name: grafana
    volumes:
      - ${PWD}/fs/volumes/grafana/provisioning:/etc/grafana/provisioning:Z
      - ${PWD}/fs/volumes/grafana/dashboards:/var/lib/grafana/dashboards:Z
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "13000:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  prometheus_data: {}
  grafana_data: {}
