global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load rules once and periodically evaluate them
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "clickhouse-01"
    static_configs:
      - targets: ["clickhouse-01:9363"]

  - job_name: "clickhouse-02"
    static_configs:
      - targets: ["clickhouse-02:9363"]

  - job_name: "clickhouse-03"
    static_configs:
      - targets: ["clickhouse-03:9363"]

  - job_name: "clickhouse-04"
    static_configs:
      - targets: ["clickhouse-04:9363"]
